import ClientProvider from "../ClientProvider";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Omnisell - SHOWCASE",
  description: "Generated by create next app",
  icons: {
    icon: "/logo-sw-fav.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ClientProvider>
          <Navbar />
          <main className="flex-grow container mx-auto px-4 py-8 min-h-screen ">
            {children}
          </main>
          <Footer />
        </ClientProvider>
      </body>
    </html>
  );
}
